require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  DisplayCopNames: true
  Exclude:
    - "bin/*"

Style/DocumentationMethod:
  RequireForNonPublicMethods: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Naming/MethodParameterName:
  AllowedNames: [io, id, to, by, on, in, at, ip, db, cv]

# Disable metrics cops

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
